/**
 * LOCKED — Approved daily PDF layout (templates/MilePilot_APPROVED_Report_Template.pdf)
 * White professional document. Data injection only — do not redesign.
 */
import PDFDocument from "pdfkit";

const BRAND = {
  navy: "#031126",
  text: "#06112A",
  muted: "#64748B",
  blue: "#0D6BFF",
  border: "#DDE6F2",
  light: "#F7F9FC",
  green: "#10B981",
};

const PDF_FOOTER_LINE = "Drive • Track • Claim";
const TOTAL_PAGES = 5;

function money(v) {
  return "£" + Number(v || 0).toFixed(2);
}

function fmtShiftTime(sec) {
  const s = Math.max(0, Number(sec) || 0);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  if (h <= 0) return `${m}m`;
  return `${h}h ${String(m).padStart(2, "0")}m`;
}

function fmtClock(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
}

function fmtDateShort(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" });
}

function drawApprovedHeader(doc, a, margin, contentW, pageW) {
  let y = 44;
  doc.fillColor(BRAND.text).font("Helvetica-Bold").fontSize(20);
  doc.text("Mile ", margin, y, { continued: true, lineBreak: false });
  doc.fillColor(BRAND.blue).text("Pilot", { continued: true, lineBreak: false });
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(9).text(` ${a.reportId}`, { lineBreak: false });
  y += 26;
  if (a.driver) {
    doc.fillColor(BRAND.text).font("Helvetica-Bold").fontSize(12).text(a.driver, margin, y);
    y += 18;
  }
  doc.fillColor(BRAND.blue).font("Helvetica-Bold").fontSize(9).text(PDF_FOOTER_LINE, margin, y);
  y += 14;
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(8.5);
  doc.text("Automatically generated by MilePilot", margin, y);
  y += 12;
  doc.text("Helping self-employed professionals stay organised.", margin, y);
  y += 12;
  doc.fillColor(BRAND.blue).text("www.milepilot.uk", margin, y);
  y += 14;
  doc.fillColor(BRAND.muted).text(`${a.generatedAt} · ${a.reportId}`, margin, y);
  doc.moveTo(margin, y + 16).lineTo(margin + contentW, y + 16).strokeColor(BRAND.border).lineWidth(0.5).stroke();
  return y + 32;
}

function drawApprovedFooter(doc, a, margin, contentW, pageNum) {
  const footY = doc.page.height - 48;
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(8);
  doc.text(`— ${pageNum} of ${TOTAL_PAGES} —`, margin, footY, { width: contentW, align: "center" });
}

function drawSectionHeading(doc, margin, y, title, subtitle = null) {
  doc.fillColor(BRAND.blue).font("Helvetica-Bold").fontSize(8).text(title.toUpperCase(), margin, y, { characterSpacing: 1.2 });
  y += 16;
  if (subtitle) {
    doc.fillColor(BRAND.text).font("Helvetica").fontSize(11).text(subtitle, margin, y);
    y += 20;
  }
  return y;
}

function drawBulletList(doc, margin, y, contentW, items) {
  doc.fillColor(BRAND.text).font("Helvetica").fontSize(10);
  items.forEach((item) => {
    doc.text(`• ${item}`, margin, y, { width: contentW, lineGap: 2 });
    y += doc.heightOfString(`• ${item}`, { width: contentW }) + 6;
  });
  return y;
}

function buildTodayHighlights(a) {
  const items = [
    `${a.totals.mi.toFixed(1)} business miles`,
    `${a.totals.journeys} ${a.totals.journeys === 1 ? "journey" : "journeys"}`,
    `${fmtShiftTime(a.totals.sec)} driving`,
    `${money(a.totals.hmrc)} HMRC value`,
  ];
  if (a.avgMilesShift > 0) {
    items.push(`Average journey ${a.avgMilesShift.toFixed(1)} miles`);
  }
  return items;
}

function buildIntelligenceBullets(a) {
  const bullets = [];
  if (a.prevTotals.mi > 0 && Math.abs(a.miDiff) >= 0.1) {
    const pct = Math.round((a.totals.mi / a.prevTotals.mi - 1) * 100);
    if (Math.abs(pct) >= 1) {
      bullets.push(`You've driven ${Math.abs(pct)}% ${pct > 0 ? "further" : "less"} than yesterday.`);
    }
  }
  if (a.busiest) {
    bullets.push(`${a.busiest.day} was your busiest day.`);
  }
  if (a.avgMilesShift > 0 && a.shifts.length >= 2) {
    bullets.push(`Average journey ${a.avgMilesShift.toFixed(1)} miles across ${a.totals.journeys} journeys.`);
  }
  if (a.weekComparePct !== null) {
    bullets.push(
      `You drove ${Math.abs(a.weekComparePct)}% ${a.weekComparePct >= 0 ? "more" : "less"} business miles this week than last week.`
    );
  }
  if (a.weekTotals.hmrc > 0) {
    const monthlyEst = a.weekTotals.hmrc * 4.33;
    bullets.push(`You're on track for approximately ${money(monthlyEst)} HMRC allowance this month.`);
  }
  if (a.longest) {
    bullets.push(`Longest shift this week: ${fmtShiftTime(a.longest.seconds)}.`);
  }
  if (!bullets.length) {
    bullets.push("MilePilot is learning your regular business journey patterns.");
  }
  return bullets;
}

function buildAiSummary(a) {
  const busiest = a.busiest ? a.busiest.day : "this period";
  const intro = `This week you drove ${a.weekTotals.mi.toFixed(1)} miles across ${a.weekTotals.journeys} business ${a.weekTotals.journeys === 1 ? "journey" : "journeys"}. ${busiest} was your busiest day. Average shift ${fmtShiftTime(a.weekAvgShiftSec)}. Estimated HMRC allowance ${money(a.weekTotals.hmrc)}.`;
  const bullets = [
    "Patterns improve as MilePilot learns your regular business journeys.",
    "Review and confirm each journey before it appears in official reports.",
    "Personal journeys stay excluded from business mileage totals.",
  ];
  return { intro, bullets };
}

function drawStatRow(doc, margin, y, contentW, stats) {
  const colW = contentW / stats.length;
  stats.forEach((s, i) => {
    const x = margin + i * colW;
    doc.fillColor(BRAND.muted).font("Helvetica-Bold").fontSize(7.5).text(s.label.toUpperCase(), x, y, { width: colW - 8 });
    doc.fillColor(BRAND.text).font("Helvetica-Bold").fontSize(12).text(s.value, x, y + 14, { width: colW - 8 });
  });
  return y + 40;
}

function drawJourneyTable(doc, a, margin, y, contentW) {
  const cols = [margin, margin + 72, margin + 118, margin + 168, margin + 228, margin + 288];
  doc.roundedRect(margin, y, contentW, 22, 4).fill(BRAND.navy);
  ["Date", "Start", "End", "Miles", "Time", "Type"].forEach((h, i) => {
    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(7.5).text(h.toUpperCase(), cols[i], y + 7);
  });
  y += 22;
  if (!a.shifts.length) {
    doc.fillColor(BRAND.muted).font("Helvetica").fontSize(10).text("No journeys recorded in this period.", margin, y + 10);
    return y + 36;
  }
  a.shifts.forEach((s, idx) => {
    doc.rect(margin, y, contentW, 22).fill(idx % 2 === 0 ? "#FFFFFF" : BRAND.light);
    doc.fillColor(BRAND.text).font("Helvetica").fontSize(8.5);
    doc.text(fmtDateShort(s.startISO), cols[0], y + 7, { width: 68 });
    doc.text(fmtClock(s.startISO), cols[1], y + 7);
    doc.text(fmtClock(s.endISO), cols[2], y + 7);
    doc.text(`${Number(s.miles || 0).toFixed(1)} miles`, cols[3], y + 7);
    doc.text(fmtShiftTime(s.seconds), cols[4], y + 7);
    doc.fillColor(BRAND.green).text("BUSINESS", cols[5], y + 7);
    y += 22;
  });
  return y;
}

function drawHmrcBox(doc, a, margin, y, contentW) {
  const boxH = 88;
  doc.roundedRect(margin, y, contentW, boxH, 12).fillAndStroke("#EEF4FF", BRAND.blue);
  doc.fillColor(BRAND.text).font("Helvetica-Bold").fontSize(12).text("HMRC SUMMARY", margin + 16, y + 14);
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(9);
  doc.text(`Current HMRC rate ${Math.round(a.hmrcRate * 100)}p per mile`, margin + 16, y + 34);
  doc.text(`Business miles ${a.totals.mi.toFixed(1)}`, margin + 16, y + 48);
  doc.text(`Estimated allowance ${money(a.totals.hmrc)}`, margin + 16, y + 62);
  doc.fontSize(7.5).text("Estimates for record keeping only. Verify before filing.", margin + 16, y + boxH - 16);
  return y + boxH + 16;
}

/** Build the locked 5-page daily PDF matching the approved template. */
export function buildApprovedDailyPdf(a) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 0, size: "A4", autoFirstPage: true });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageW = doc.page.width;
    const margin = 52;
    const contentW = pageW - margin * 2;

    // ── Page 1: Daily Business Summary ──
    let y = drawApprovedHeader(doc, a, margin, contentW, pageW);
    y = drawSectionHeading(doc, margin, y, "Daily Business Summary", a.generatedAt);
    doc.fillColor(BRAND.muted).font("Helvetica-Bold").fontSize(8).text("TODAY'S BUSINESS MILES", margin, y);
    y += 16;
    doc.fillColor(BRAND.text).font("Helvetica-Bold").fontSize(72).text(a.totals.mi.toFixed(1), margin, y, { lineBreak: false });
    y += 82;
    doc.fillColor(BRAND.muted).font("Helvetica").fontSize(11).text("Business Miles Recorded", margin, y);
    y += 28;
    y = drawStatRow(doc, margin, y, contentW, [
      { label: "Business Miles", value: a.totals.mi.toFixed(1) },
      { label: "Driving Time", value: fmtShiftTime(a.totals.sec) },
      { label: "Journeys", value: String(a.totals.journeys) },
      { label: "Mileage Value", value: money(a.totals.hmrc) },
    ]);
    y += 12;
    doc.fillColor(BRAND.blue).font("Helvetica-Bold").fontSize(8).text("TODAY'S HIGHLIGHTS", margin, y);
    y += 16;
    y = drawBulletList(doc, margin, y, contentW, buildTodayHighlights(a));
    drawApprovedFooter(doc, a, margin, contentW, 1);

    // ── Page 2: MilePilot Intelligence ──
    doc.addPage({ margin: 0 });
    y = drawApprovedHeader(doc, a, margin, contentW, pageW);
    y = drawSectionHeading(doc, margin, y, "MilePilot Intelligence", "Useful patterns from your business mileage records.");
    y = drawBulletList(doc, margin, y, contentW, buildIntelligenceBullets(a));
    drawApprovedFooter(doc, a, margin, contentW, 2);

    // ── Page 3: Business Journey Log + HMRC ──
    doc.addPage({ margin: 0 });
    y = drawApprovedHeader(doc, a, margin, contentW, pageW);
    y = drawSectionHeading(doc, margin, y, "Business Journey Log", "Professional record for your accountant");
    y = drawJourneyTable(doc, a, margin, y, contentW);
    y += 12;
    y = drawHmrcBox(doc, a, margin, y, contentW);
    drawApprovedFooter(doc, a, margin, contentW, 3);

    // ── Page 4: Weekly Performance ──
    doc.addPage({ margin: 0 });
    y = drawApprovedHeader(doc, a, margin, contentW, pageW);
    y = drawSectionHeading(doc, margin, y, "Weekly Performance", `Week ending ${a.weekEnding}`);
    y = drawStatRow(doc, margin, y, contentW, [
      { label: "Business Miles", value: `${a.weekTotals.mi.toFixed(1)} miles` },
      { label: "Business Journeys", value: String(a.weekTotals.journeys) },
      { label: "Average Shift", value: fmtShiftTime(a.weekAvgShiftSec) },
      { label: "Mileage Value", value: money(a.weekTotals.hmrc) },
    ]);
    y += 8;
    if (a.weekComparePct !== null) {
      doc.fillColor(BRAND.muted).font("Helvetica-Bold").fontSize(8).text("WEEKLY TREND", margin, y);
      y += 14;
      doc.fillColor(BRAND.text).font("Helvetica").fontSize(10).text(
        `${a.weekComparePct >= 0 ? "+" : ""}${a.weekComparePct}% vs last week`,
        margin,
        y
      );
      y += 24;
    }
    doc.fillColor(BRAND.blue).font("Helvetica-Bold").fontSize(8).text("BUSINESS INSIGHTS", margin, y);
    y += 16;
    drawBulletList(doc, margin, y, contentW, buildIntelligenceBullets(a).slice(0, 4));
    drawApprovedFooter(doc, a, margin, contentW, 4);

    // ── Page 5: MilePilot AI Summary ──
    doc.addPage({ margin: 0 });
    y = drawApprovedHeader(doc, a, margin, contentW, pageW);
    y = drawSectionHeading(doc, margin, y, "MilePilot AI Summary");
    const ai = buildAiSummary(a);
    doc.fillColor(BRAND.text).font("Helvetica").fontSize(10).text(ai.intro, margin, y, { width: contentW, lineGap: 3 });
    y += doc.heightOfString(ai.intro, { width: contentW }) + 16;
    drawBulletList(doc, margin, y, contentW, ai.bullets);
    drawApprovedFooter(doc, a, margin, contentW, 5);

    doc.end();
  });
}
