import express from "express";
import cors from "cors";
import PDFDocument from "pdfkit";
import dotenv from "dotenv";
import { Resend } from "resend";

dotenv.config();

const app = express();

app.use(cors());
app.use(express.json({ limit: "2mb" }));

const resend = new Resend(process.env.RESEND_API_KEY);

function money(v) {
  return "£" + Number(v || 0).toFixed(2);
}

function buildPdfBuffer(report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48 });
    const chunks = [];

    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(30).fillColor("#06112A").text("Mile", { continued: true }).fillColor("#0D6BFF").text("Pilot");
    doc.moveDown(0.2).fontSize(11).fillColor("#64748B").text("We track and send reports on auto pilot.");
    doc.moveDown(1);

    doc.fontSize(18).fillColor("#06112A").text(`${report.period || "Daily"} Mileage Report`);
    doc.moveDown(0.8);

    doc.fontSize(12).fillColor("#06112A");
    doc.text(`Total miles: ${Number(report.totals?.miles || 0).toFixed(2)}`);
    doc.text(`Driving time: ${report.totals?.time || "0h 00m"}`);
    doc.text(`Estimated HMRC claim: ${money(report.totals?.hmrc)}`);

    doc.moveDown(1);
    doc.fontSize(15).text("Shift Breakdown");
    doc.moveDown(0.4);

    const shifts = report.shifts || [];

    if (!shifts.length) {
      doc.fontSize(11).text("No shifts saved yet.");
    }

    shifts.forEach((s, i) => {
      doc.fontSize(11)
        .fillColor("#06112A")
        .text(`${i + 1}. ${s.date || ""} • ${s.vehicle || ""} • ${Number(s.miles || 0).toFixed(2)} miles • ${money(s.hmrc)}`);
    });

    doc.moveDown(1.5)
      .fontSize(9)
      .fillColor("#64748B")
      .text("Generated by MilePilot. HMRC figures are estimates for record keeping and should be checked against official guidance.");

    doc.end();
  });
}

app.get("/health", (req, res) => {
  res.json({
    ok: true,
    resendConfigured: !!process.env.RESEND_API_KEY,
    from: process.env.EMAIL_FROM || "MilePilot <reports@milepilot.uk>",
  });
});

app.post("/reports/send", async (req, res) => {
  try {
    const report = req.body;

    if (!process.env.RESEND_API_KEY) {
      return res.status(500).json({
        sent: false,
        message: "RESEND_API_KEY is missing in Railway variables",
      });
    }

    if (!report.email) {
      return res.status(400).json({
        sent: false,
        message: "Email is required",
      });
    }

    const pdf = await buildPdfBuffer(report);

    const result = await resend.emails.send({
      from: process.env.EMAIL_FROM || "MilePilot <reports@milepilot.uk>",
      to: report.email,
      subject: `MilePilot ${report.period || "Daily"} Mileage Report`,
      text: `Your MilePilot ${report.period || "Daily"} report is attached.`,
      attachments: [
        {
          filename: `milepilot-${String(report.period || "daily").toLowerCase()}-report.pdf`,
          content: pdf.toString("base64"),
        },
      ],
    });

    if (result.error) {
      console.error("Resend error:", result.error);
      return res.status(500).json({
        sent: false,
        message: result.error.message || "Resend failed",
      });
    }

    console.log("Email sent:", result.data?.id);

    return res.json({
      sent: true,
      messageId: result.data?.id || null,
    });
  } catch (err) {
    console.error("Email send failed:", err);
    return res.status(500).json({
      sent: false,
      message: err.message || "Email send failed",
    });
  }
});

app.listen(process.env.PORT || 8787, () => {
  console.log("MilePilot backend running on port " + (process.env.PORT || 8787));
});
