/**
 * CRITICAL MILEAGE ENGINE FILE
 * Do not edit this file for UI-only changes.
 * Any change here requires regression testing for:
 * - GPS tracking
 * - background tracking
 * - auto trip ending
 * - mileage calculation
 * - report generation
 * - email delivery
 *
 * VITAL — BUSINESS CRITICAL (MP-043)
 * Expo WebView shell — loads PWA and bridges native GPS.
 * Do not modify without reading docs/TRACKING_CONTRACT.md
 */
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, Platform, SafeAreaView, StatusBar, StyleSheet, View } from 'react-native';
import { WebView } from 'react-native-webview';
import Constants from 'expo-constants';
import { setBackgroundLocationForwarder, takePendingBackgroundLocations } from './locationTask';
import { handleWebViewMessage, injectLocationIntoWebView } from './expoLocationBridge';
import { setNativeAutoEndInjector, flushPendingNativeAutoEnd } from './nativeAutoEnd';

const WEB_APP_URL = Constants.expoConfig?.extra?.webAppUrl || 'https://app.milepilot.uk/?runtime=expo';

/**
 * Injected before MilePilot HTML loads — exposes bridge to tracking-provider.js
 */
const BRIDGE_BOOT_SCRIPT = `
(function(){
  window.__MILEPILOT_EXPO__ = true;
  window.__MILEPILOT_RUNTIME__ = 'expo';
  document.documentElement.classList.add('mp-expo');
  window.__expoBridgeCallbacks = {};
  window.__expoBridgeReceive = function(msg) {
    try {
      if (msg && msg.type === 'expo:location' && window.__onExpoNativeLocation) {
        window.__onExpoNativeLocation(msg);
      }
      if (msg && msg.type === 'expo:autoend:trigger' && typeof window.__onExpoAutoEnd === 'function') {
        window.__onExpoAutoEnd(msg);
      }
      if (msg && msg.id && window.__expoBridgeCallbacks[msg.id]) {
        window.__expoBridgeCallbacks[msg.id](msg);
        delete window.__expoBridgeCallbacks[msg.id];
      }
    } catch (e) { console.error('[MPExpoBridge]', e); }
  };
  window.MPExpoBridge = {
    post: function(raw) {
      if (window.ReactNativeWebView) {
        window.ReactNativeWebView.postMessage(typeof raw === 'string' ? raw : JSON.stringify(raw));
      }
    },
    request: function(type, payload) {
      return new Promise(function(resolve) {
        var id = 'e' + Date.now() + Math.random().toString(36).slice(2, 8);
        window.__expoBridgeCallbacks[id] = resolve;
        window.MPExpoBridge.post({ type: type, id: id, payload: payload || {} });
      });
    }
  };
})();
true;
`;

export default function MilePilotWebView() {
  const webViewRef = useRef(null);
  const [ready, setReady] = useState(false);

  const sendToWebView = useCallback((payload) => {
    injectLocationIntoWebView(webViewRef, payload);
  }, []);

  useEffect(() => {
    setBackgroundLocationForwarder((payload) => {
      sendToWebView(payload);
    });
    setNativeAutoEndInjector(() => {
      injectLocationIntoWebView(webViewRef, { type: 'expo:autoend:trigger', timestamp: Date.now() });
    });
    return () => {
      setBackgroundLocationForwarder(null);
      setNativeAutoEndInjector(null);
    };
  }, [sendToWebView]);

  useEffect(() => {
    const flushBufferedLocations = () => {
      takePendingBackgroundLocations().forEach((payload) => {
        sendToWebView(payload);
      });
    };
    const sub = AppState.addEventListener('change', (nextState) => {
      if (nextState === 'active') {
        flushBufferedLocations();
        flushPendingNativeAutoEnd();
      }
    });
    return () => sub.remove();
  }, [sendToWebView]);

  const onMessage = useCallback(
    (event) => {
      handleWebViewMessage(event.nativeEvent.data, sendToWebView);
    },
    [sendToWebView]
  );

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#031126" />
      {!ready && (
        <View style={styles.loading}>
          <ActivityIndicator size="large" color="#0D6BFF" />
        </View>
      )}
      <WebView
        ref={webViewRef}
        source={{ uri: WEB_APP_URL }}
        style={[styles.webview, !ready && styles.hidden]}
        onLoadEnd={() => setReady(true)}
        onMessage={onMessage}
        injectedJavaScriptBeforeContentLoaded={BRIDGE_BOOT_SCRIPT}
        geolocationEnabled
        allowsInlineMediaPlayback
        javaScriptEnabled
        domStorageEnabled
        sharedCookiesEnabled
        originWhitelist={['*']}
        setSupportMultipleWindows={false}
        // iOS: allow geolocation prompt from WebView content
        {...(Platform.OS === 'ios' ? { allowsBackForwardNavigationGestures: false } : {})}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#031126',
  },
  webview: {
    flex: 1,
    backgroundColor: '#031126',
  },
  hidden: {
    opacity: 0,
  },
  loading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#031126',
    zIndex: 2,
  },
});
